events {}
http {
    server {
        listen 8000;
        location /kk/ {
            rewrite ^/kk/(.*) /$1 break;
            proxy_pass http://127.0.0.1:8001;
        }
        location /deepseek/ {
            rewrite ^/deepseek/(.*) /$1 break;
            proxy_pass http://127.0.0.1:8002;
        }
    }
}
